"use strict";
angular.module("reportService", [])
	.factory("reportService", [function() {
        var factories = {};
        // flush data every 30s
        factories.elementData = {
            "h":{
                "h1":{
                    tag:"h1",
                    class:"editable-h1",
                    attr:{},
                    style:{
                        width:'',
                        height:'',
                        color:'',
                        'text-align':'',
                        'font-size':'',
                        'font-weight':'',
                        'margin-top':'',
                        'margin-bottom':'',
                        'margin-left':'',
                        'margin-right':'',
                        'padding-top':'',
                        'padding-left':'',
                        'padding-bottom':'',
                        'padding-right':'',
                        'background-color':''
                    }
                },
                "h2":{
                    tag:"h2",
                    class:"editable-h2",
                    attr:{},
                    style:{
                        width:'',
                        height:'',
                        color:'',
                        'text-align':'',
                        'font-size':'',
                        'font-weight':'',
                        'margin-top':'',
                        'margin-bottom':'',
                        'margin-left':'',
                        'margin-right':'',
                        'padding-top':'',
                        'padding-left':'',
                        'padding-bottom':'',
                        'padding-right':'',
                        'background-color':''
                    }
                },
                "h3":{
                    tag:"h3",
                    class:"editable-h3",
                    attr:{},
                    style:{
                        width:'',
                        height:'',
                        color:'',
                        'text-align':'',
                        'font-size':'',
                        'font-weight':'',
                        'margin-top':'',
                        'margin-bottom':'',
                        'margin-left':'',
                        'margin-right':'',
                        'padding-top':'',
                        'padding-left':'',
                        'padding-bottom':'',
                        'padding-right':'',
                        'background-color':''
                    }
                },
                "h4":{
                    tag:"h4",
                    class:"editable-h4",
                    attr:{},
                    style:{
                        width:'',
                        height:'',
                        color:'',
                        'text-align':'',
                        'font-size':'',
                        'font-weight':'',
                        'margin-top':'',
                        'margin-bottom':'',
                        'margin-left':'',
                        'margin-right':'',
                        'padding-top':'',
                        'padding-left':'',
                        'padding-bottom':'',
                        'padding-right':'',
                        'background-color':''
                    }
                },
                "h5":{
                    tag:"h5",
                    class:"editable-h5",
                    attr:{},
                    style:{
                        width:'',
                        height:'',
                        color:'',
                        'text-align':'',
                        'font-size':'',
                        'font-weight':'',
                        'margin-top':'',
                        'margin-bottom':'',
                        'margin-left':'',
                        'margin-right':'',
                        'padding-top':'',
                        'padding-left':'',
                        'padding-bottom':'',
                        'padding-right':'',
                        'background-color':''
                    }
                },
                "h6":{
                    tag:"h6",
                    class:"editable-h6",
                    attr:{},
                    style:{
                        width:'',
                        height:'',
                        color:'',
                        'text-align':'',
                        'font-size':'',
                        'font-weight':'',
                        'margin-top':'',
                        'margin-bottom':'',
                        'margin-left':'',
                        'margin-right':'',
                        'padding-top':'',
                        'padding-left':'',
                        'padding-bottom':'',
                        'padding-right':'',
                        'background-color':''
                    }
                }
            },
            "p":{
                tag:"p",
                class:"editable-p",
                attr:{},
                style:{
                    width:'',
                    height:'',
                    color:'',
                    'text-align':'',
                    'font-size':'',
                    'font-weight':'',
                    'margin-top':'',
                    'margin-bottom':'',
                    'margin-left':'',
                    'margin-right':'',
                    'padding-top':'',
                    'padding-left':'',
                    'padding-bottom':'',
                    'padding-right':'',
                    'background-color':''
                }
            },
            "img":{
                tag:"img",
                class:"editable-img",
                attr:{},
                style:{
                    width:'',
                    height:'',
                    'align':'',
                    'margin-top':'',
                    'margin-bottom':'',
                    'margin-left':'',
                    'margin-right':'',
                    'padding-top':'',
                    'padding-left':'',
                    'padding-bottom':'',
                    'padding-right':''
                }
            },
        };

        return factories;
    }]);
